### PR TITLE
Restrict route-agent /run to /run/xtables.lock

### LINKED ISSUE #1432: Mount xtables.lock file in Route-agent Pod.
**What happened**:
Please see the following issue for more details - https://github.com/submariner-io/submariner-operator/issues/1430

Currently, Route-agent Pod mounts the [entire "/run" folder](https://github.com/submariner-io/submariner-operator/commit/eeab0ae6fe7b8241632e675ca5052373c8fa53e7) of the host inside the route-agent Pod. From a security POV, we can just mount what we really require and avoid mounting the entire directory.

### PR DESCRIPTION
**Pull request by skitt**
The route agent doesn't need all of /run, only /run/xtables.lock (for
iptables).

Fixes: #1432
Signed-off-by: Stephen Kitt <skitt@redhat.com>

### CODE REVIEW

**Review by mangelajo — CHANGES_REQUESTED** [review]
I'm not sure about this one, I may need to test it with ovn, where we need to access the local ovs db, I believe there is a db sock in that directory. I'll give it a try on an OVN deployment and report back to this thread.

**Comment by skitt** [comment]
> I'm not sure about this one, I may need to test it with ovn, where we need to access the local ovs db, I believe there is a db sock in that directory. I'll give it a try on an OVN deployment and report back to this thread.

Yup, I’ll be keeping an eye on the OVN e2e as well. I’ll update the patch to add whatever OVN needs, and document it.

**Comment by mangelajo** [comment]
> > I'm not sure about this one, I may need to test it with ovn, where we need to access the local ovs db, I believe there is a db sock in that directory. I'll give it a try on an OVN deployment and report back to this thread.
> 
> Yup, I’ll be keeping an eye on the OVN e2e as well. I’ll update the patch to add whatever OVN needs, and document it.

Oh right, we have CI, let's see how that works :)

**Comment by skitt** [comment]
> I'm not sure about this one, I may need to test it with ovn, where we need to access the local ovs db, I believe there is a db sock in that directory. I'll give it a try on an OVN deployment and report back to this thread.

Adding `/run/openvswitch/db.sock` was indeed required.

**Review by dfarrell07 — APPROVED** [review]

**Review by tpantelis — APPROVED** [review]

**Comment by skitt** [comment]
@mangelajo could you update your review?

**Comment by skitt** [comment]
@mangelajo ping

**Review by mangelajo — APPROVED** [review]

**Comment by mangelajo** [comment]
> @mangelajo ping

sorry for the delay, approved.

**Review by sridhargaddam — APPROVED** [review]

**Pull request merged**
