### PR TITLE
Fix issue with ConfigMap update

### PR DESCRIPTION
**Pull request by aswinsuryan**
Fixes: #692
Signed-off-by: Aswin Surayanarayanan <asuryana@redhat.com>

### CODE REVIEW

**Comment by mangelajo** [comment]
@aswinsuryan , can you explain what are you trying to fix? , and reference an issue? Otherwise it's a bit hard to figure out just from the code :-)

**Review by mangelajo — CHANGES_REQUESTED** [review]
Also in my experience unit testing it would help you test this out better, since it's not something we really test in E2E but in D/S openshift testing. You can always split in smaller functions to help unit test

**Comment by aswinsuryan** [comment]
> Also in my experience unit testing it would help you test this out better, since it's not something we really test in E2E but in D/S openshift testing. You can always split in smaller functions to help unit test

I will add a UT for this.


> @aswinsuryan , can you explain what are you trying to fix? , and reference an issue? Otherwise it's a bit hard to figure out just from the code :-)

Created an issue with the error https://github.com/submariner-io/submariner-operator/issues/692

**Comment by mangelajo** [comment]
> > Also in my experience unit testing it would help you test this out better, since it's not something we really test in E2E but in D/S openshift testing. You can always split in smaller functions to help unit test
> 
> I will add a UT for this.
> 
> > @aswinsuryan , can you explain what are you trying to fix? , and reference an issue? Otherwise it's a bit hard to figure out just from the code :-)
> 
> Created an issue with the error #692

Thanks please add it to the commit message when updating.

**Comment by aswinsuryan** [comment]
> > > Also in my experience unit testing it would help you test this out better, since it's not something we really test in E2E but in D/S openshift testing. You can always split in smaller functions to help unit test
> > 
> > 
> > I will add a UT for this.
> > > @aswinsuryan , can you explain what are you trying to fix? , and reference an issue? Otherwise it's a bit hard to figure out just from the code :-)
> > 
> > 
> > Created an issue with the error #692
> 
> Thanks please add it to the commit message when updating.

Added UT and updated the comments. I will add more UT for other methods in a separate patch

**Review by mangelajo — APPROVED** [review]
Thanks for including a test suite.

**Review by skitt — APPROVED** [review]

**Review by skitt — APPROVED** [review]

**Pull request merged**
