### PR TITLE
Enable gocritic linting, fix errors

### PR DESCRIPTION
**Pull request by dfarrell07**
Signed-off-by: Daniel Farrell <dfarrell@redhat.com>

### CODE REVIEW

**Comment by mangelajo** [comment]
looks good, is there any way to avoid it complaining for the CIDR ->cIDR ?

**Comment by dfarrell07** [comment]
> looks good, is there any way to avoid it complaining for the CIDR ->cIDR ?

It seems to me it's a correct complaint, as it should be a local var with lowercase first letter, right?

**Comment by dfarrell07** [comment]
FYI I'm splitting up the gocritic enabled-tags per commit for easier review.

**Comment by tpantelis** [comment]
> > looks good, is there any way to avoid it complaining for the CIDR ->cIDR ?
> 
> It seems to me it's a correct complaint, as it should be a local var with lowercase first letter, right?

How about we just name the param `type`?

**Comment by dfarrell07** [comment]
> > > looks good, is there any way to avoid it complaining for the CIDR ->cIDR ?
> > 
> > 
> > It seems to me it's a correct complaint, as it should be a local var with lowercase first letter, right?
> 
> How about we just name the param `type`?

I'm down to rename it, but `type` is a Go builtin (or similar) and causes a failure.

```
ERRO Running error: buildir: analysis skipped: errors in package: [/go/src/github.com/submariner-io/submariner-operator/pkg/subctl/cmd/join.go:275:66: expected type, found 'type' /go/src/github.com/submariner-io/submariner-operator/pkg/subctl/cmd/join.go:285:8: expected 'IDENT', found ',' /go/src/github.com/submariner-io/submariner-operator/pkg/subctl/cmd/join.go:286:10: expected operand, found 'type' /go/src/github.com/submariner-io/submariner-operator/pkg/subctl/cmd/join.go:275:66: expected type, found 'type' /go/src/github.com/submariner-io/submariner-operator/pkg/subctl/cmd/join.go:285:8: expected 'IDENT', found ',' /go/src/github.com/submariner-io/submariner-operator/pkg/subctl/cmd/join.go:286:10: expected operand, found 'type'] 
```

**Comment by dfarrell07** [comment]
> How about `cidrType`?

I think that gets us back to needing `cIDRType` lol. :smile:

**Comment by dfarrell07** [comment]
> > How about `cidrType`?
> 
> I think that gets us back to needing `cIDRType` lol.

Talking with @tpantelis on Slack, it turns out the rule for CamelCase here is `cidrType`, and that's not inconsistent with `typeCIDR` we use elsewhere. Thanks Tom, I learned something!

**Pull request merged**
