### PR TITLE
Add permission RBAC  to access endpoints

### LINKED ISSUE #191: Update the Submariner-operator to remove network-pulgin syncer deployment
Update the Submariner-operator to remove network-pulgin syncer deployment

### PR DESCRIPTION
**Pull request by aswinsuryan**
With OVN IC submariner operator needs read access to endpoints to understand the OVN topology

Fixes: https://github.com/submariner-io/enhancements/issues/191

### CODE REVIEW

**Comment by tpantelis** [comment]
> With OVN IC submariner operator needs read access to endpoints to understand the OVN topology

Can you explain why? And why not EndpointSlices?

**Comment by aswinsuryan** [comment]
@tpantelis This for OVN, ovn creates endpoints without a service if IC is enabled in multiple nodes per zone configuration. No endpoints will be created if it is in single zone per node configuration. We need this information to decide how we should connect to ovndb

Since the number of endpoints will be less than number of nodes , I don't think they will have plan to move to endpoint slices. If they move in future , we will have to update too.

**Comment by aswinsuryan** [comment]
This will be used by https://github.com/submariner-io/submariner-operator/pull/2726

**Review by skitt — APPROVED** [review]

**Review by yboaron — APPROVED** [review]

**Review by tpantelis — APPROVED** [review]

**Comment by dfarrell07** [comment]
[E2E (1.25, ovn)](https://github.com/submariner-io/submariner-operator/actions/runs/5576260098/jobs/10187278997?pr=2728#logs) timed out, re-running.

**Pull request merged**
