### PR TITLE
Use only two clusters for E2E

### PR DESCRIPTION
**Pull request by mkolesnik**
We don't really need 3 clusters, use only 2 for testing the operator
works.

### CODE REVIEW

**Comment by dfarrell07** [comment]
What's the best way for us to squash these merge commits before merging? It feels a bit aggressive to just force-push to Mike's branch like GH is suggesting, but maybe that's right.

**Comment by mkolesnik** [comment]
> What's the best way for us to squash these merge commits before merging? It feels a bit aggressive to just force-push to Mike's branch like GH is suggesting, but maybe that's right.

It's just one commit, all the others are "merge master".
So you can "squash and merge" and it'll squash it all info the original commit.

If it was more than one commit originally, we'd have to manually rebase.

**Comment by dfarrell07** [comment]
> > What's the best way for us to squash these merge commits before merging? It feels a bit aggressive to just force-push to Mike's branch like GH is suggesting, but maybe that's right.
> 
> It's just one commit, all the others are "merge master".
> So you can "squash and merge" and it'll squash it all info the original commit.
> 
> If it was more than one commit originally, we'd have to manually rebase.

Oh that's awesome, I hadn't noticed that GH feature!

**Comment by skitt** [comment]
@mkolesnik could you add your sign-off?

**Comment by mkolesnik** [comment]
> @mkolesnik could you add your sign-off?

Yeah, had to force push it

**Pull request merged**
