### PR TITLE
Revert pr 1951 and merge branch devel into feature-multi-active-gw

### PR DESCRIPTION
**Pull request by anfredette**
Merge branch 'devel' into feature-multi-active-gw-update

### CODE REVIEW

**Review by dfarrell07 — APPROVED** [review]

**Comment by dfarrell07** [comment]
It might make sense to remove the revert commit from this PR, handle it in a distinct PR like https://github.com/submariner-io/submariner-operator/pull/2025.

**Review by Billy99 — APPROVED** [review]

**Comment by dfarrell07** [comment]
> It might make sense to remove the revert commit from this PR, handle it in a distinct PR like #2025.

Or better still, just merge them together here (discussion on revert PR). I'd consider noting the revert in the PR title/description.

**Comment by anfredette** [comment]
@dfarrell07 github will let me squash and merge, but not rebase and merge because "This branch cannot be rebased due to conflicts".  I think we want the rebase to preserve the commit history. Any ideas?

**Comment by anfredette** [comment]
I did a `git rebase upstream/feature-multi-active-gw` back in my forked branch.  It rearranged some things, but it looks like it's all there.  I'll try pushing that to see if it resolves the conflicts.

**Pull request merged**
