### PR TITLE
Fix FindPodCommandParameter method when value contains '='

### PR DESCRIPTION
**Pull request by jinglina**
when I use this method to find parameter "--feature-gates", it show in kube-apiserver pods like this : 
**--feature-gates=ServerSideApply=true,IPv6DualStack=true**
it gets 'ServerSideApply' as --feature-gates value.
this is not right.

### CODE REVIEW

**Review by skitt — APPROVED** [review]

**Review by tpantelis — APPROVED** [review]

**Comment by dfarrell07** [comment]
This seems to be causing the system tests ([Deployment](https://github.com/submariner-io/submariner-operator/actions/runs/4729438042/jobs/8402138154?pr=2601#logs), [Deployment (globalnet)](https://github.com/submariner-io/submariner-operator/actions/runs/4729438042/jobs/8402138600?pr=2601#logs)) to fail with:

> [15:15:03.043] [dir=submariner-operator; cl=cluster1; fn=kubectl]$ command kubectl --context=cluster1 get secrets -n submariner-k8s-broker -o jsonpath={.items[?(@.metadata.annotations['kubernetes\.io/service-account\.name']=='submariner-k8s-broker-client')].metadata.name}
Failed to find the secret's name

**Comment by tpantelis** [comment]
> This seems to be causing the system tests ([Deployment](https://github.com/submariner-io/submariner-operator/actions/runs/4729438042/jobs/8402138154?pr=2601#logs), [Deployment (globalnet)](https://github.com/submariner-io/submariner-operator/actions/runs/4729438042/jobs/8402138600?pr=2601#logs)) to fail with:
> 
> > [15:15:03.043] [dir=submariner-operator; cl=cluster1; fn=kubectl]$ command kubectl --context=cluster1 get secrets -n submariner-k8s-broker -o jsonpath={.items[?(@.metadata.annotations['kubernetes.io/service-account.name']=='submariner-k8s-broker-client')].metadata.name}
> > Failed to find the secret's name

This PR isn't causing that - it's caused by https://github.com/submariner-io/subctl/pull/653 which removed the `submariner-k8s-broker-client `SA et al. We're seeing it now after a new `subctl` with that change was published. I think we can just remove the `verify_subm_broker_secrets()` check.

**Comment by tpantelis** [comment]
> This PR isn't causing that - it's caused by [submariner-io/subctl#653](https://github.com/submariner-io/subctl/pull/653) which removed the `submariner-k8s-broker-client` SA et al. We're seeing it now after a new `subctl` with that change was published. I think we can just remove the `verify_subm_broker_secrets()` check.

I'm not so sure - I commented on https://github.com/submariner-io/subctl/pull/653.

**Review by dfarrell07 — APPROVED** [review]

**Comment by dfarrell07** [comment]
Thanks for the PR @jinglina! :1st_place_medal:

**Comment by jinglina** [comment]
thanks

**Review by sridhargaddam — APPROVED** [review]

**Pull request merged**
