### PR TITLE
Create xtables.lock as a file if it doesn't already exist

### PR DESCRIPTION
**Pull request by skitt**
Default host path mounts create a directory if the mounted path doesn't correspond to anything, which ends up breaking iptables. This fixes that by ensuring that xtables.lock is created as a file if it doesn't already exist; subsequent invocations of iptables on the host (if any) will then be able to use the new file for locking.

### CODE REVIEW

**Comment by tpantelis** [comment]
This seems to cause a vulnerability error.

**Comment by skitt** [comment]
> This seems to cause a vulnerability error.

The vulnerability is a false positive, see https://github.com/github/advisory-database/pull/2742

**Comment by tpantelis** [comment]
> The vulnerability is a false positive, see [github/advisory-database#2742](https://github.com/github/advisory-database/pull/2742)

OK. I changed the job to required - did you make it non-required due to this?

**Comment by skitt** [comment]
> OK. I changed the job to required - did you make it non-required due to this?

Yes — we can wait for the advisory fix to be merged, or “unrequire” the job until it’s fixed...

**Review by dfarrell07 — APPROVED** [review]

**Review by tpantelis — APPROVED** [review]

**Review by sridhargaddam — APPROVED** [review]

**Pull request merged**
