### PR TITLE
Revert "Add support for `subctl join ... --multi-active-gateway=true`…

### PR DESCRIPTION
**Pull request by anfredette**
Revert "Add support for `subctl join --multi-active-gateway=true`… (#1951)"

This reverts commit a7d50c0853975c0c773db345972d0caa45137171.

This commit was inadvertantly pulled in while the feature-multi-active-gw
branch was being created.

Signed-off-by: Andre Fredette <afredette@redhat.com>

### CODE REVIEW

**Review by Billy99 — APPROVED** [review]

**Review by astoycos — APPROVED** [review]

**Comment by dfarrell07** [comment]
The Go linter errors are because this is running with golangci-lint 1.44.2 but not the fixes in 7d102174b86b1c70de182a1e90e31896cd605da0. This revert works in CI with https://github.com/submariner-io/submariner-operator/pull/2026 / https://github.com/submariner-io/submariner-operator/pull/2026/commits/7d102174b86b1c70de182a1e90e31896cd605da0.

**Comment by Billy99** [comment]
> The Go linter errors are because this is running with golangci-lint 1.44.2 but not the fixes in [7d10217](https://github.com/submariner-io/submariner-operator/commit/7d102174b86b1c70de182a1e90e31896cd605da0). This revert works in CI with #2026 / [7d10217](https://github.com/submariner-io/submariner-operator/commit/7d102174b86b1c70de182a1e90e31896cd605da0).

@dfarrell07 Is there a way to override/bypass so this can merge?

**Comment by dfarrell07** [comment]
Is there some reason to not merge this commit as a part of https://github.com/submariner-io/submariner-operator/pull/2026? That PR has this same revert I think, rebased on top of the fix for these Go linter issues.

**Comment by anfredette** [comment]
The files with the lint errors are changed significantly in devel, and will be pulled in by the next merge commit.

**Comment by anfredette** [comment]
> Is there some reason to not merge this commit as a part of #2026? That PR has this same revert I think, rebased on top of the fix for these Go linter issues.

I was just trying to keep the revert separate from the merge, but that would solve the lint problem.

**Comment by dfarrell07** [comment]
I guess it would also be possible to send the merge/rebase PR and then a revert PR, which would separate the two and not require changing the required jobs.

**Comment by anfredette** [comment]
> I guess it would also be possible to send the merge/rebase PR and then a revert PR, which would separate the two and not require changing the required jobs.

The problem is that if I don't do the revert first, there are a bunch of conflicts in the merge.

**Comment by dfarrell07** [comment]
Ah okay, so IMHO it's fine to merge it all together as a CI-passing chunk in https://github.com/submariner-io/submariner-operator/pull/2026.

**Comment by anfredette** [comment]
We're going to try to do this revert as part of the merge from devel.

**Pull request closed without merging**
