### PR TITLE
Add JUnit report generation to "subctl verify"

### PR DESCRIPTION
**Pull request by MaxBab**
The E2E tests should be able to generate report at the end of the
execution.
After the following ginkgo patch - [1], creation of the test directory
(if required) and generation of the report handled by ginkgo after the
input parameters such as directory and file name.

Replacing existing parameters which are no longer working after the
following patch - [2].

[1] - https://github.com/onsi/ginkgo/pull/601
[2] - https://github.com/submariner-io/shipyard/pull/216

Depends on: https://github.com/submariner-io/shipyard/pull/755

Signed-off-by: Maxim Babushkin <mbabushk@redhat.com>

### CODE REVIEW

**Review by skitt — APPROVED** [review]

**Comment by MaxBab** [comment]
The dependency patch needs to be merged first.
Then I'll take care on this one.

https://github.com/submariner-io/shipyard/pull/755

**Comment by dfarrell07** [comment]
FYI, `Depends on` should not have a colon (or we should modify the config to accept colons).

**Comment by MaxBab** [comment]
> FYI, `Depends on` should not have a colon (or we should modify the config to accept colons).

Thanks.
Will keep that in mind.

**Comment by MaxBab** [comment]
@skitt @dfarrell07 

Guys, I guess once the https://github.com/submariner-io/shipyard/pull/755 will be merged, in additional to the existing changes, the `go.mod` file will need to be updated in order to pull the right state from the shipyard repo.
Am I right?

**Comment by skitt** [comment]
> Guys, I guess once the [submariner-io/shipyard#755](https://github.com/submariner-io/shipyard/pull/755) will be merged, in additional to the existing changes, the `go.mod` file will need to be updated in order to pull the right state from the shipyard repo. Am I right?

That’s right, you’ll need to run `go get github.com/submariner-io/shipyard@devel && go mod vendor && go mod tidy` and commit the changes to `go.mod` and `go.sum`.

**Comment by MaxBab** [comment]
> > Guys, I guess once the [submariner-io/shipyard#755](https://github.com/submariner-io/shipyard/pull/755) will be merged, in additional to the existing changes, the `go.mod` file will need to be updated in order to pull the right state from the shipyard repo. Am I right?
> 
> That’s right, you’ll need to run `go get github.com/submariner-io/shipyard@devel && go mod vendor && go mod tidy` and commit the changes to `go.mod` and `go.sum`.

Thanks!

**Comment by MaxBab** [comment]
I have updated the references to submariner and lighthouse in additional to the shipyard, because without it, the build of subctl fails with the following error:

```
# github.com/submariner-io/lighthouse/test/e2e/framework
vendor/github.com/submariner-io/lighthouse/test/e2e/framework/framework.go:573:60: cannot use framework.ExecOptions{...} (type framework.ExecOptions) as type *framework.ExecOptions in argument to f.Framework.ExecWithOptions
# github.com/submariner-io/submariner/test/e2e/framework
vendor/github.com/submariner-io/submariner/test/e2e/framework/dataplane.go:199:36: cannot use execOptions (type framework.ExecOptions) as type *framework.ExecOptions in argument to p.Framework.ExecWithOptions
make: *** [Makefile:192: bin/subctl-devel-1826d30-linux-amd64] Error 2
[05:43:41.648] [submariner-operator]$ make --debug=b bin/subctl
make: *** [Makefile.dapper:43: bin/subctl] Error 2
```

**Review by Jaanki — APPROVED** [review]

**Comment by skitt** [comment]
> I have updated the references to submariner and lighthouse in additional to the shipyard, because without it, the build of subctl fails with the following error:
> 
> ```
> # github.com/submariner-io/lighthouse/test/e2e/framework
> vendor/github.com/submariner-io/lighthouse/test/e2e/framework/framework.go:573:60: cannot use framework.ExecOptions{...} (type framework.ExecOptions) as type *framework.ExecOptions in argument to f.Framework.ExecWithOptions
> # github.com/submariner-io/submariner/test/e2e/framework
> vendor/github.com/submariner-io/submariner/test/e2e/framework/dataplane.go:199:36: cannot use execOptions (type framework.ExecOptions) as type *framework.ExecOptions in argument to p.Framework.ExecWithOptions
> make: *** [Makefile:192: bin/subctl-devel-1826d30-linux-amd64] Error 2
> [05:43:41.648] [submariner-operator]$ make --debug=b bin/subctl
> make: *** [Makefile.dapper:43: bin/subctl] Error 2
> ```

Ah, yes, we forgot to run the 0.13.0-m0 release after the 0.12 branch...

**Comment by MaxBab** [comment]
Rebased the patch as it showed as outdated regarding the devel branch.

**Pull request merged**
