### PR TITLE
Split out an API module

### LINKED ISSUE #1542: Publish the APIs as a separate module
Projects using the Submariner Operator APIs need to depend on the whole Submariner Operator project, which tends to cause dependency tree issues.

We can publish the APIs as a separate module, without needing a separate repository; see https://golang.org/ref/mod for details. Providing `github.com/submariner-io/submariner-operator/apis` as a separate module would allow other projects to depend on only that.

### PR DESCRIPTION
**Pull request by skitt**
This allows dependent projects that are only interested in the API
(such as submariner-addon) to only import the API.

Fixes: #1542
Signed-off-by: Stephen Kitt <skitt@redhat.com>

### CODE REVIEW

**Comment by skitt** [comment]
Depends on https://github.com/submariner-io/submariner/pull/1536

**Comment by tpantelis** [comment]
Should we remove the _pkg/versions/versions.go_ file as well or do that later? We'll have to change the release process to modify the new file.

**Comment by skitt** [comment]
> Should we remove the _pkg/versions/versions.go_ file as well or do that later? We'll have to change the release process to modify the new file.

I thought I’d done that, I see I’d only added the new version in `apis` but left the old one. I’ll fix that right away.

**Review by tpantelis — APPROVED** [review]
Should we remove the _pkg/versions/versions.go_ file as well?

**Comment by dfarrell07** [comment]
> Depends on [submariner-io/submariner#1536](https://github.com/submariner-io/submariner/pull/1536)

That has only been merged for 15m, but re-running CI it's still failing with related:

```
go: github.com/submariner-io/submariner@v0.10.0-rc1.0.20210816112556-6e4bb78fab88 requires
	github.com/submariner-io/submariner/pkg/apis@v0.0.0: reading https://proxy.golang.org/github.com/submariner-io/submariner/pkg/apis/@v/v0.0.0.mod: 410 Gone
	server response: not found: github.com/submariner-io/submariner/pkg/apis@v0.0.0: invalid version: unknown revision pkg/apis/v0.0.0
make: *** [/opt/shipyard/Makefile.inc:166: vendor/modules.txt] Error 1
```

**Comment by skitt** [comment]
> > Depends on [submariner-io/submariner#1536](https://github.com/submariner-io/submariner/pull/1536)
> 
> That has only been merged for 15m, but re-running CI it's still failing with related:
> 
> ```
> go: github.com/submariner-io/submariner@v0.10.0-rc1.0.20210816112556-6e4bb78fab88 requires
> 	github.com/submariner-io/submariner/pkg/apis@v0.0.0: reading https://proxy.golang.org/github.com/submariner-io/submariner/pkg/apis/@v/v0.0.0.mod: 410 Gone
> 	server response: not found: github.com/submariner-io/submariner/pkg/apis@v0.0.0: invalid version: unknown revision pkg/apis/v0.0.0
> make: *** [/opt/shipyard/Makefile.inc:166: vendor/modules.txt] Error 1
> ```

Yes, the dependency in `go.mod` needs to be updated to the commit with the updated submariner → submariner APIs dependency.

**Review by dfarrell07 — APPROVED** [review]

**Pull request merged**
