### PR TITLE
Use the controller runtime client

### PR DESCRIPTION
**Pull request by skitt**
The general-purpose client is currently initialised using the OpenShift Cluster DNS operator, probably accidentally. This initialises it using the controller runtime directly, dropping the Cluster DNS dependency.

Signed-off-by: Stephen Kitt <skitt@redhat.com>

### CODE REVIEW

**Comment by skitt** [comment]
We have this dependency going all the way back to at least 0.12; this should be backported to 0.14, 0.13 and 0.12 to reduce our dependency tree and resulting exposure to security alerts.

**Review by tpantelis — APPROVED** [review]

**Review by Jaanki — APPROVED** [review]

**Comment by tpantelis** [comment]
K8s 1.17 job is failing consistently: `ERROR: failed to create cluster: failed to init node with kubeadm...`.  Perhaps we should make it non-required for now so we don't bock PRs....

**Comment by skitt** [comment]
> K8s 1.17 job is failing consistently: `ERROR: failed to create cluster: failed to init node with kubeadm...`. Perhaps we should make it non-required for now so we don't bock PRs....

Yes, we lost the ability to work with 1.17 at some point :-/.

**Review by sridhargaddam — APPROVED** [review]

**Comment by sridhargaddam** [comment]
@vthapar @aswinsuryan one of the service-discovery tests are failing. Is this some known flaky issue or something new which you want to take a look?

```
[Fail] [discovery] Test Headless Service Discovery Across Clusters when the number of active pods backing a service changes [It] should resolve the local pod IPs 
github.com/submariner-io/shipyard@v0.14.0-m2.0.20221121173616-41b20b7d46e1/test/e2e/framework/framework.go:562
```

**Pull request merged**
