### PR TITLE
Provide a deploy command to deploy on all clusters

### PR DESCRIPTION
**Pull request by skitt**
This adds a deploy command which will take care of the broker and any
number of “client” clusters.

Signed-off-by: Stephen Kitt <skitt@redhat.com>

---
This change is [Reviewable](https://reviewable.io/reviews/submariner-io/submariner-operator/62)

### CODE REVIEW

**Comment by mangelajo** [comment]
I'm all fine with introducing this behavior, although the other seems more natural to me (deploy-broker, join join...) more step-wise for the admins.

**Comment by skitt** [comment]
> I'm all fine with introducing this behavior, although the other seems more natural to me (deploy-broker, join join...) more step-wise for the admins.

Yes, in practice it’s rather unwieldy. There are a few cleanups and additions which are useful more generally IMO, I’ll split them out into separate commits (in particular, not overwriting the detected CIDRs, and supporting contexts).

**Comment by mangelajo** [comment]
Supporting contexts would be a great addition :-)

**Comment by mangelajo** [comment]
@skitt should we close this one for now?, we can re-open to continue work in the future, or if we take patches from here. (trying to zero-inbox our PRs) :-)

**Comment by skitt** [comment]
> @skitt should we close this one for now?, we can re-open to continue work in the future, or if we take patches from here. (trying to zero-inbox our PRs) :-)

Let’s close it for now, I’ve pushed the branch with your suggested change, I’ll re-open it if necessary later.

**Pull request closed without merging**
