### PR TITLE
Remove networkplugin syncer deployment

### LINKED ISSUE #191: Update the Submariner-operator to remove network-pulgin syncer deployment
Update the Submariner-operator to remove network-pulgin syncer deployment

### PR DESCRIPTION
**Pull request by tpantelis**
The controller now deletes the Deployment and associated RBAC resources.

Fixes https://github.com/submariner-io/enhancements/issues/191
Depends on: https://github.com/submariner-io/submariner/pull/2621

### CODE REVIEW

**Review by dfarrell07 — APPROVED** [review]

**Comment by aswinsuryan** [comment]
LGTM , @vthapar I think this does some part of https://github.com/submariner-io/enhancements/issues/193

**Review by aswinsuryan — APPROVED** [review]

**Comment by aswinsuryan** [comment]
The OVN test should pass once this is merged https://github.com/submariner-io/submariner/pull/2621

**Comment by sridhargaddam** [comment]
> The OVN test should pass once this is merged [submariner-io/submariner#2621](https://github.com/submariner-io/submariner/pull/2621)

Added a Depends on in the commit message.

**Comment by aswinsuryan** [comment]
@tpantelis the ovn failure now seems to be related to uninstall.

**Comment by tpantelis** [comment]
> @tpantelis the ovn failure now seems to be related to uninstall.

Looks an issue with the route agent uninstall on the submariner side. Maybe it’s crashing.

**Comment by tpantelis** [comment]
> Looks an issue with the route agent uninstall on the submariner side. Maybe it’s crashing.

```
panic: close of nil channel

  goroutine 1 [running]:
  github.com/submariner-io/submariner/pkg/routeagent_driver/handlers/ovn.(*GatewayRouteController).stop(...)
  	github.com/submariner-io/submariner/pkg/routeagent_driver/handlers/ovn/gateway_route_controller.go:138
  github.com/submariner-io/submariner/pkg/routeagent_driver/handlers/ovn.(*Handler).Stop(0xc000131ef0, 0x1)
  	github.com/submariner-io/submariner/pkg/routeagent_driver/handlers/ovn/uninstall.go:29 +0x31
https://github.com/submariner-io/submariner/pull/2652
```

https://github.com/submariner-io/submariner/pull/2652

**Review by skitt — APPROVED** [review]

**Pull request merged**
