### PR TITLE
Allow submariner-globalnet role to create endpoints

### LINKED ISSUE #1844: Allow submariner-globalnet role to create endpoints
**What would you like to be added**:
Allow submariner-globalnet role to create endpoints.

**Why is this needed**:
This is needed  for service without selector to work with globalnet (original and internal endpoints needs to be synced).
xref: submariner-io/submariner#1695

### PR DESCRIPTION
**Pull request by mkimuram**
What would you like to be added:
This PR allows submariner-globalnet role to create endpoints.

Why is this needed:
xref: https://github.com/submariner-io/submariner/pull/1695
fixes: https://github.com/submariner-io/submariner-operator/issues/1844

### CODE REVIEW

**Comment by mkimuram** [comment]
Note that https://github.com/submariner-io/submariner-operator/pull/1582 was to grant the role to handle endpoints, but it didn't add create right. Also, it directly edited the file under bundle/manifests directory, not the file under config/rbac.

**Review by sridhargaddam — APPROVED** [review]

**Comment by sridhargaddam** [comment]
@mkimuram we would need a similar fix in submariner-charts - https://github.com/submariner-io/submariner-charts/blob/devel/submariner-operator/templates/rbac.yaml

**Review by tpantelis — APPROVED** [review]

**Review by dfarrell07 — APPROVED** [review]

**Review by dfarrell07 — CHANGES_REQUESTED** [review]
The embedded YAMLs need to be updated.

```
diff --git a/pkg/embeddedyamls/yamls.go b/pkg/embeddedyamls/yamls.go
index 3[5](https://github.com/submariner-io/submariner-operator/runs/5187992012?check_suite_focus=true#step:4:5)b7389..9130800 100[6](https://github.com/submariner-io/submariner-operator/runs/5187992012?check_suite_focus=true#step:4:6)44
--- a/pkg/embeddedyamls/yamls.go
+++ b/pkg/embeddedyamls/yamls.go
@@ -2852,6 +2852,[7](https://github.com/submariner-io/submariner-operator/runs/5187992012?check_suite_focus=true#step:4:7) @@ rules:
       - ""
     resources:
       - services
+      - endpoints
     verbs:
       - create
       - get
```

Looking at the GHA, it seems like you just need to run `make pkg/embeddedyamls/yamls.go`.

https://github.com/submariner-io/submariner-operator/runs/5187992012?check_suite_focus=true

+1 otherwise, can feel free to dismiss my review once that CI is passing (currently not required but maybe it should be?).

**Comment by mkimuram** [comment]
@dfarrell07  Thank you for pointing it out. I've updated embedded YAMLs.

**Comment by dfarrell07** [comment]
Both the Lighthouse jobs were failing, re-running them now.

**Review by dfarrell07 — APPROVED** [review]
The Lighthouse failures don't seem to be related to this PR, they are happening elsewhere (https://github.com/submariner-io/submariner-operator/pull/1849).

**Review by tpantelis — APPROVED** [review]

**Pull request merged**
