### PR TITLE
Use SHAs for all GHA versions

### PR DESCRIPTION
**Pull request by dfarrell07**
Per GitHub's security guidelines, GHAs should be pinned using full
length commit SHAs instead of tags.

The SHAs are of the commits currently resolved by the versions.

Even "trusted" GHAs from GitHub developers are pinned because it's
possible their repo right could be compromised and a malicious GHA
published. These core repos are not frequently substantially updated.

Submariner-internal GHAs are left pinned at devel because we want
automatic updates from Shipyard's shared tooling.

Signed-off-by: Daniel Farrell <dfarrell@redhat.com>

### CODE REVIEW

**Comment by dfarrell07** [comment]
It seems like the update of yamllint has highlighted new issues. 

https://github.com/submariner-io/submariner-operator/pull/1526/checks?check_run_id=3256447545

**Comment by skitt** [comment]
I think the switch to SHAs shouldn’t bump the versions, *i.e.* the SHA used here should be the one matching the tag. Bumping should be done separately.

**Comment by skitt** [comment]
> It seems like the update of yamllint has highlighted new issues.
> 
> https://github.com/submariner-io/submariner-operator/pull/1526/checks?check_run_id=3256447545

That one’s weird, yamllint isn’t upgraded in this PR, is it?

**Comment by dfarrell07** [comment]
> I think the switch to SHAs shouldn’t bump the versions, _i.e._ the SHA used here should be the one matching the tag. Bumping should be done separately.

Makes sense, I've updated the PR to the SHAs resolved by the current versions (accounting for tags like v2 resolving to 2.*). I'll send different commits/PRs to update the versions.

**Comment by dfarrell07** [comment]
> > It seems like the update of yamllint has highlighted new issues.
> > https://github.com/submariner-io/submariner-operator/pull/1526/checks?check_run_id=3256447545
> 
> That one’s weird, yamllint isn’t upgraded in this PR, is it?

Yeah, good point. I can replicate this locally on devel.

**Comment by dfarrell07** [comment]
> > > It seems like the update of yamllint has highlighted new issues.
> > > https://github.com/submariner-io/submariner-operator/pull/1526/checks?check_run_id=3256447545
> > 
> > 
> > That one’s weird, yamllint isn’t upgraded in this PR, is it?
> 
> Yeah, good point. I can replicate this locally on devel.

This is really weird. I sent a fix, but see https://github.com/submariner-io/submariner-operator/pull/1527#issuecomment-894408408.

**Comment by dfarrell07** [comment]
> > I think the switch to SHAs shouldn’t bump the versions, _i.e._ the SHA used here should be the one matching the tag. Bumping should be done separately.
> 
> Makes sense, I've updated the PR to the SHAs resolved by the current versions. I'll send different commits/PRs to update the versions.

I updated actions/upload-artifact here: https://github.com/submariner-io/submariner-operator/pull/1529

It's actually the only GHA dependency here that needs an update I think. The others are either the latest commit (for not very active projects) or recent/latest release (for active projects, where we can expect regular releases).

**Review by skitt — APPROVED** [review]

**Review by tpantelis — APPROVED** [review]

**Pull request merged**
