### PR TITLE
Increase inotfy settings for prometheus job

### PR DESCRIPTION
**Pull request by Jaanki**
... to make it pass. Currently the job fails due to lower settings.

https://github.com/submariner-io/submariner-operator/runs/7630710149?check_suite_focus=true#step:4:44892

Signed-off-by: Janki Chhatbar <jchhatba@redhat.com>

### CODE REVIEW

**Review by mkolesnik — CHANGES_REQUESTED** [review]
> ... to make it pass. Currently the job fails due to lower settings.
> 
> https://github.com/submariner-io/submariner-operator/runs/7630710149?check_suite_focus=true#step:4:44892

Where did you see it fail?

The link you gave is not for this job..

Anyhow the actual failure is
```
[04:39:02.955] [submariner-operator]$ [cluster2] kubectl apply -f /opt/shipyard/scripts/resources/prometheus/clusterrole.yaml
[04:39:02.957] [submariner-operator]$ [cluster2] command kubectl --context=cluster2 apply -f /opt/shipyard/scripts/resources/prometheus/clusterrole.yaml
[cluster2] error: resource mapping not found for name: "prometheus" namespace: "" from "/opt/shipyard/scripts/resources/prometheus/clusterrole.yaml": no matches for kind "ClusterRole" in version "rbac.authorization.k8s.io/v1beta1"
```

Which is not related to inotify.

**Comment by Jaanki** [comment]
> > ... to make it pass. Currently the job fails due to lower settings.
> > https://github.com/submariner-io/submariner-operator/runs/7630710149?check_suite_focus=true#step:4:44892
> 
> Where did you see it fail?
> 
> The link you gave is not for this job..
> 
> Anyhow the actual failure is
> 
> ```
> [04:39:02.955] [submariner-operator]$ [cluster2] kubectl apply -f /opt/shipyard/scripts/resources/prometheus/clusterrole.yaml
> [04:39:02.957] [submariner-operator]$ [cluster2] command kubectl --context=cluster2 apply -f /opt/shipyard/scripts/resources/prometheus/clusterrole.yaml
> [cluster2] error: resource mapping not found for name: "prometheus" namespace: "" from "/opt/shipyard/scripts/resources/prometheus/clusterrole.yaml": no matches for kind "ClusterRole" in version "rbac.authorization.k8s.io/v1beta1"
> ```
> 
> Which is not related to inotify.

The failure is here:
https://github.com/submariner-io/submariner-operator/runs/7634396383?check_suite_focus=true#step:4:44892

```
[cluster2] Max attempts reached, failed to run 'create_kind_cluster'!
[15:09:14.023] [submariner-operator]$ [cluster2] exit 1
Failed to create kind clusters.
[15:09:14.027] [submariner-operator]$ [cluster2] warn_inotify
[15:09:14.030] [submariner-operator]$ [cluster2] warn_inotify
[15:09:14.034] [submariner-operator]$ [cluster2] cat /proc/sys/fs/inotify/max_user_instances
Your inotify settings are lower than our recommendation.
This may cause failures in large deployments, but we don't know if it caused this failure.
[15:09:14.039] [submariner-operator]$ [cluster2] cat /proc/sys/fs/inotify/max_user_watches
[15:09:14.043] [submariner-operator]$ [cluster2] cat /proc/sys/fs/inotify/max_user_instances
You may need to increase your inotify settings (currently 54107 and 128):
sudo sysctl fs.inotify.max_user_watches=524288
sudo sysctl fs.inotify.max_user_instances=512
See https://kind.sigs.k8s.io/docs/user/known-issues/#pod-errors-due-to-too-many-open-files
[15:09:14.048] [submariner-operator]$ [cluster2] exit 1
make: *** [Makefile.inc:133: clusters] Error 1
[15:09:14.057] [submariner-operator]$ make --debug=b deploy
make: *** [Makefile.dapper:46: deploy] Error 2
```

**Comment by mkolesnik** [comment]
> 
> The failure is here: https://github.com/submariner-io/submariner-operator/runs/7634396383?check_suite_focus=true#step:4:44892
> 

Again the actual failure in that one is https://github.com/submariner-io/submariner-operator/runs/7634396383?check_suite_focus=true#step:4:982

**Comment by dfarrell07** [comment]
> Your inotify settings are lower than our recommendation.
This may cause failures in large deployments, but we don't know if it caused this failure.

I did this a number of times too, tried to reduce false inotify positives like the `we don't know if it caused this failure` help message.

**Comment by skitt** [comment]
The Prometheus deployment failure is fixed by https://github.com/submariner-io/shipyard/pull/904

**Comment by Jaanki** [comment]
https://github.com/submariner-io/shipyard/pull/904 resolves the issue and hence closing this.

**Pull request closed without merging**
