### PR TITLE
Updates to fix grpc and docker CVEs

### PR DESCRIPTION
**Pull request by dfarrell07**
See commit messages for details.

### CODE REVIEW

**Comment by dfarrell07** [comment]
There still an issue with `go.opentelemetry.io/contrib/instrumentation/net/http/otelhttp@v0.35.1` that I'm not sure how to resolve.

```
[~/go/src/submariner-io/submariner-operator]$ go get -u go.opentelemetry.io/contrib/instrumentation/net/http/otelhttp                                                                                                         [release-0.15]
go: downloading go.opentelemetry.io/contrib/instrumentation/net/http/otelhttp v0.45.0
go: downloading go.opentelemetry.io/contrib/instrumentation/net/http v0.11.0
go: downloading go.opentelemetry.io/contrib v1.20.0
go: downloading go.opentelemetry.io v0.1.0
go: downloading go.opentelemetry.io/otel v1.19.0
go: downloading go.opentelemetry.io/otel/metric v1.19.0
go: downloading go.opentelemetry.io/otel/trace v1.19.0
go: downloading github.com/go-logr/logr v1.3.0
go: upgraded github.com/go-logr/logr v1.2.3 => v1.3.0
go: upgraded github.com/stretchr/testify v1.8.1 => v1.8.4
go: upgraded go.opentelemetry.io/contrib/instrumentation/net/http/otelhttp v0.35.1 => v0.45.0
go: upgraded go.opentelemetry.io/otel v1.11.0 => v1.19.0
go: upgraded go.opentelemetry.io/otel/metric v0.31.0 => v1.19.0
go: upgraded go.opentelemetry.io/otel/trace v1.11.0 => v1.19.0
[~/go/src/submariner-io/submariner-operator]$ go mod tidy                                                                                                                                                                    *[release-0.15]
go: finding module for package go.opentelemetry.io/otel/exporters/otlp/internal/envconfig
go: finding module for package go.opentelemetry.io/otel/exporters/otlp/internal
go: downloading go.opentelemetry.io/otel/exporters/otlp v0.20.1
github.com/submariner-io/submariner-operator imports
	github.com/operator-framework/operator-sdk/cmd/operator-sdk imports
	github.com/operator-framework/operator-sdk/internal/cmd/operator-sdk/cli imports
	github.com/operator-framework/operator-sdk/internal/cmd/operator-sdk/bundle imports
	github.com/operator-framework/operator-sdk/internal/cmd/operator-sdk/bundle/validate imports
	github.com/operator-framework/api/pkg/validation imports
	github.com/operator-framework/api/pkg/validation/internal imports
	k8s.io/apiextensions-apiserver/pkg/apis/apiextensions/validation imports
	k8s.io/apiserver/pkg/util/webhook imports
	k8s.io/component-base/tracing imports
	go.opentelemetry.io/otel/exporters/otlp/otlptrace/otlptracegrpc imports
	go.opentelemetry.io/otel/exporters/otlp/internal: module go.opentelemetry.io/otel/exporters/otlp@latest found (v0.20.1), but does not contain package go.opentelemetry.io/otel/exporters/otlp/internal
github.com/submariner-io/submariner-operator imports
	github.com/operator-framework/operator-sdk/cmd/operator-sdk imports
	github.com/operator-framework/operator-sdk/internal/cmd/operator-sdk/cli imports
	github.com/operator-framework/operator-sdk/internal/cmd/operator-sdk/bundle imports
	github.com/operator-framework/operator-sdk/internal/cmd/operator-sdk/bundle/validate imports
	github.com/operator-framework/api/pkg/validation imports
	github.com/operator-framework/api/pkg/validation/internal imports
	k8s.io/apiextensions-apiserver/pkg/apis/apiextensions/validation imports
	k8s.io/apiserver/pkg/util/webhook imports
	k8s.io/component-base/tracing imports
	go.opentelemetry.io/otel/exporters/otlp/otlptrace/otlptracegrpc imports
	go.opentelemetry.io/otel/exporters/otlp/otlptrace/internal/otlpconfig imports
	go.opentelemetry.io/otel/exporters/otlp/internal/envconfig: module go.opentelemetry.io/otel/exporters/otlp@latest found (v0.20.1), but does not contain package go.opentelemetry.io/otel/exporters/otlp/internal/envconfig
```

Same thing if I do `go get -u go.opentelemetry.io/contrib/instrumentation/net/http/otelhttp@v0.44.0`.

**Comment by skitt** [comment]
The otel dependencies are a pain to deal with (not through otel’s fault, and there’s been recent work in `k/k` to improve things, but we’re still left to deal with the fallout — for CVEs which mostly don’t apply to us).

**Review by skitt — APPROVED** [review]

**Comment by skitt** [comment]
The way to fix this is to look for the first “integration point” in the dependency tree for a given family of dependencies. In

```
github.com/submariner-io/submariner-operator imports
	github.com/operator-framework/operator-sdk/cmd/operator-sdk imports
	github.com/operator-framework/operator-sdk/internal/cmd/operator-sdk/cli imports
	github.com/operator-framework/operator-sdk/internal/cmd/operator-sdk/bundle imports
	github.com/operator-framework/operator-sdk/internal/cmd/operator-sdk/bundle/validate imports
	github.com/operator-framework/api/pkg/validation imports
	github.com/operator-framework/api/pkg/validation/internal imports
	k8s.io/apiextensions-apiserver/pkg/apis/apiextensions/validation imports
	k8s.io/apiserver/pkg/util/webhook imports
	k8s.io/component-base/tracing imports
	go.opentelemetry.io/otel/exporters/otlp/otlptrace/otlptracegrpc imports
	go.opentelemetry.io/otel/exporters/otlp/internal: module go.opentelemetry.io/otel/exporters/otlp@latest found (v0.20.1), but does not contain package go.opentelemetry.io/otel/exporters/otlp/internal
```

that’s the transition from `k8s.io` dependencies to `go.opentelemetry.io` dependencies, which happens with `go.opentelemetry.io/otel/exporters/otlp/otlptrace/otlptracegrpc`. That is also the integration point for the second error.

`go get go.opentelemetry.io/otel/exporters/otlp/otlptrace/otlptracegrpc` fixes the dependency tree.

**Comment by dfarrell07** [comment]
Oh I see you already added the final commit, thanks!

**Review by tpantelis — APPROVED** [review]

**Pull request merged**
