### PR TITLE
Improve calico CNI detection

### PR DESCRIPTION
**Pull request by sridhargaddam**
A K8s cluster can be installed with Calico CNI in multiple ways. It was seen that in some deployments the calico-config map is not created but we can find calico-node cni pods running as daemonSet. This PR enhances the code to look for calico-node pods when the config map is not found.

### CODE REVIEW

**Comment by sridhargaddam** [comment]
Verified this PR by manually deploying a KIND Calico cluster using the following instructions.
https://docs.tigera.io/calico/latest/getting-started/kubernetes/kind

**Review by tpantelis — APPROVED** [review]

**Comment by sridhargaddam** [comment]
I'm seeing the following errors in the CI jobs.

```
[18:52:54.574] [dir=submariner-operator; cl=cluster1; fn=verify_subm_deployed]$ verify_network_plugin_syncer
[18:52:54.578] [dir=submariner-operator; cl=cluster1; fn=verify_network_plugin_syncer]$ kubectl get sa --namespace=submariner-operator submariner-networkplugin-syncer
[18:52:54.582] [dir=submariner-operator; cl=cluster1; fn=kubectl]$ command kubectl --context=cluster1 get sa --namespace=submariner-operator submariner-networkplugin-syncer
[cluster1] Error from server (NotFound): serviceaccounts "submariner-networkplugin-syncer" not found
make: *** [Makefile:124: system-test] Error 1
make: *** [Makefile.dapper:58: system-test] Error 2
```

@tpantelis do we already have some fix for this error?

**Comment by tpantelis** [comment]
> @tpantelis do we already have some fix for this error?

https://github.com/submariner-io/submariner-operator/pull/2768

**Review by dfarrell07 — APPROVED** [review]

**Comment by sridhargaddam** [comment]
Release note PR: https://github.com/submariner-io/submariner-website/pull/1011

**Pull request merged**
