### PR TITLE
Ask Admiral how to name its settings

### PR DESCRIPTION
**Pull request by skitt**
This avoids discrepancies between the environment variable names we
use in the operator and those expected by Admiral.

Depends on https://github.com/submariner-io/admiral/pull/296
Signed-off-by: Stephen Kitt <skitt@redhat.com>

### CODE REVIEW

**Comment by m4ce** [comment]
@skitt - is this PR going to fix the issue?

**Comment by skitt** [comment]
> @skitt - is this PR going to fix the issue?

It will ensure the “insecure” flag is actually taken into account, yes.

**Comment by Hitesh-Agrawal** [comment]
> > @skitt - is this PR going to fix the issue?
> 
> It will ensure the “insecure” flag is actually taken into account, yes.

@skitt Would appreciate if you could let us know how to test this change once completed. Which version on submariner-operator helm-chart we should use along with the respective  docker image for submariner-operator , gateway and route-agent. Thx.

**Review by dfarrell07 — APPROVED** [review]

**Comment by skitt** [comment]
> > > @skitt - is this PR going to fix the issue?
> > 
> > 
> > It will ensure the “insecure” flag is actually taken into account, yes.
> 
> @skitt Would appreciate if you could let us know how to test this change once completed. Which version on submariner-operator helm-chart we should use along with the respective docker image for submariner-operator , gateway and route-agent. Thx.

@Hitesh-Agrawal I know you’re in a hurry to get this working; I’ll let you know once everything is ready.

**Review by tpantelis — APPROVED** [review]

**Pull request merged**
