### PR TITLE
Add Sonar unit test coverage reporting

### PR DESCRIPTION
**Pull request by dfarrell07**
Add GHA to run unit tests, generate coverage report, and upload the report to SonarCloud.

Add configuration to ignore code that shouldn't count for coverage.

Relates-to: stolostron/backlog#22706
Signed-off-by: Daniel Farrell <dfarrell@redhat.com>

### CODE REVIEW

**Review by tpantelis — APPROVED** [review]

**Review by nyechiel — APPROVED** [review]

**Comment by dfarrell07** [comment]
> SonarCloud Quality Gate failed.    [Quality Gate failed](https://sonarcloud.io/dashboard?id=submariner-io_submariner-operator&pullRequest=2263)
> 
> [Bug](https://sonarcloud.io/project/issues?id=submariner-io_submariner-operator&pullRequest=2263&resolved=false&types=BUG) [A](https://sonarcloud.io/project/issues?id=submariner-io_submariner-operator&pullRequest=2263&resolved=false&types=BUG) [0 Bugs](https://sonarcloud.io/project/issues?id=submariner-io_submariner-operator&pullRequest=2263&resolved=false&types=BUG) [Vulnerability](https://sonarcloud.io/project/issues?id=submariner-io_submariner-operator&pullRequest=2263&resolved=false&types=VULNERABILITY) [A](https://sonarcloud.io/project/issues?id=submariner-io_submariner-operator&pullRequest=2263&resolved=false&types=VULNERABILITY) [0 Vulnerabilities](https://sonarcloud.io/project/issues?id=submariner-io_submariner-operator&pullRequest=2263&resolved=false&types=VULNERABILITY) [Security Hotspot](https://sonarcloud.io/project/security_hotspots?id=submariner-io_submariner-operator&pullRequest=2263&resolved=false&types=SECURITY_HOTSPOT) [A](https://sonarcloud.io/project/security_hotspots?id=submariner-io_submariner-operator&pullRequest=2263&resolved=false&types=SECURITY_HOTSPOT) [0 Security Hotspots](https://sonarcloud.io/project/security_hotspots?id=submariner-io_submariner-operator&pullRequest=2263&resolved=false&types=SECURITY_HOTSPOT) [Code Smell](https://sonarcloud.io/project/issues?id=submariner-io_submariner-operator&pullRequest=2263&resolved=false&types=CODE_SMELL) [A](https://sonarcloud.io/project/issues?id=submariner-io_submariner-operator&pullRequest=2263&resolved=false&types=CODE_SMELL) [0 Code Smells](https://sonarcloud.io/project/issues?id=submariner-io_submariner-operator&pullRequest=2263&resolved=false&types=CODE_SMELL)
> 
> [No Coverage information](https://sonarcloud.io/component_measures?id=submariner-io_submariner-operator&pullRequest=2263) No Coverage information [](https://sonarcloud.io/component_measures?id=submariner-io_submariner-operator&pullRequest=2263&metric=new_duplicated_lines_density&view=list) [3.1% Duplication](https://sonarcloud.io/component_measures?id=submariner-io_submariner-operator&pullRequest=2263&metric=new_duplicated_lines_density&view=list)

I think this is happening because we enabled it via the UI but we don't have this PR merged yet to add config.

**Comment by dfarrell07** [comment]
[E2E (1.25)](https://github.com/submariner-io/submariner-operator/actions/runs/3241490417/jobs/5313497586#logs)

```
 Failure [85.117 seconds]
[dataplane] Basic TCP connectivity tests across clusters without discovery
github.com/submariner-io/submariner@v0.14.0-m1.0.20220926163523-c1aa0f37d980/test/e2e/dataplane/tcp_pod_connectivity.go:28
  when a pod with HostNetworking connects via TCP to a remote pod
  github.com/submariner-io/submariner@v0.14.0-m1.0.20220926163523-c1aa0f37d980/test/e2e/dataplane/tcp_pod_connectivity.go:109
    when the pod is not on a gateway and the remote pod is not on a gateway
    github.com/submariner-io/submariner@v0.14.0-m1.0.20220926163523-c1aa0f37d980/test/e2e/dataplane/tcp_pod_connectivity.go:117
      should have sent the expected data from the pod to the other pod [It]
      github.com/submariner-io/submariner@v0.14.0-m1.0.20220926163523-c1aa0f37d980/test/e2e/dataplane/tcp_pod_connectivity.go:36

      Expected
          <int32>: 1
      to equal
          <int32>: 0

      github.com/submariner-io/shipyard@v0.14.0-m2/test/e2e/framework/network_pods.go:184
```

Trying to re-run

**Comment by dfarrell07** [comment]
> You are running CI analysis while Automatic Analysis is enabled. Please consider disabling one or the other.

https://github.com/submariner-io/submariner-operator/actions/runs/3242198998/jobs/5315124028

**Comment by dfarrell07** [comment]
> > You are running CI analysis while Automatic Analysis is enabled. Please consider disabling one or the other.
> 
> https://github.com/submariner-io/submariner-operator/actions/runs/3242198998/jobs/5315124028

Fixed that, but now we need to add a SONAR_TOKEN for this repo and subctl (wouldn't give us a token before).

> Project not found. Please check the 'sonar.projectKey' and 'sonar.organization' properties, the 'SONAR_TOKEN' environment variable, or contact the project administrator

**Pull request merged**
