### PR TITLE
Configure replicas

### PR DESCRIPTION
**Pull request by skitt**
Depends: https://github.com/submariner-io/submariner-operator/pull/17

---
This change is [Reviewable](https://reviewable.io/reviews/submariner-io/submariner-operator/18)

### CODE REVIEW

**Comment by mangelajo** [comment]
@skitt It seems like you need to fix the verify step on the replica count:
https://travis-ci.com/submariner-io/submariner-operator/builds/134898133#L2598

And that'd be it.

**Comment by skitt** [comment]
> @skitt It seems like you need to fix the verify step on the replica count:
> https://travis-ci.com/submariner-io/submariner-operator/builds/134898133#L2598

Yes (and thanks for the review), but does that make sense? The current test checks that we’ve got as many replicas running as we requested, which is also what Kubernetes uses to consider that a service is available. So I wonder whether changing the test would only be hiding a bad design decision: I’m not sure we should request more replicas than the number of labeled nodes.

**Comment by dfarrell07** [comment]
I see the same timeouts locally as CI shows FYI.

**Comment by mangelajo** [comment]
I guess we can drop this one if we are moving to daemonset.

**Pull request closed without merging**
