### PR TITLE
Change `devel` tag to `subctl-devel`

### PR DESCRIPTION
**Pull request by mkolesnik**
Since we're changing the `master` branch name to `devel`, this tag will
collide, so change it something sensible.

Signed-off-by: Mike Kolesnik <mkolesni@redhat.com>

### CODE REVIEW

**Review by mangelajo — APPROVED** [review]
Looks good, but we will need to make changes in get.submariner.io I guess.

**Comment by skitt** [comment]
Why `subctl`? Is the tag supposed to be `subctl`-specific?

**Comment by mkolesnik** [comment]
> Why `subctl`? Is the tag supposed to be `subctl`-specific?

It's subctl bleeding edge specific, if you have other suggestions I don't mind.

**Review by skitt — CHANGES_REQUESTED** [review]
Thanks, just a minor fix: the commit message needs to be updated too ;-).

**Review by skitt — APPROVED** [review]

**Pull request merged**
