### PR TITLE
Set default value of dedicated-gw to true for GCP and RHOS

### LINKED ISSUE #1915: Cloud prepare: Switch the default dedicated mode to enabled for GCP Clusters
Currently, while preparing cloud infrastructure for GCP clusters, the default value of `--dedicated-gateway` is set as false. This should be changed to "true".

```
subctl cloud prepare gcp -h
This command prepares an OpenShift installer-provisioned infrastructure (IPI) on GCP cloud for Submariner installation.

Usage:
  subctl cloud prepare gcp [flags]

Flags:
      --credentials string        GCP credentials configuration file (default "/home/sgaddam/.gcp/osServiceAccount.json")
      --dedicated-gateway         Whether a dedicated gateway node has to be deployed (default false)
      --gateway-instance string   Type of gateway instance machine (default "n1-standard-4")
      --gateways int              Number of gateways to deploy (default 1)
  -h, --help                      help for gcp
      --infra-id string           GCP infra ID
      --ocp-metadata string       OCP metadata.json file (or the directory containing it) from which to read the GCP infra ID and region from (takes precedence over the specific flags)
      --project-id string         GCP project ID
      --region string             GCP region
```

### LINKED ISSUE #1919: RHOS Cloud prepare: Switch the default value of dedicated mode to true
Currently, while preparing cloud infrastructure for RHOS clusters, the default value of --dedicated-gateway is set as false. This should be changed to "true".

### PR DESCRIPTION
**Pull request by sridhargaddam**
Fixes: https://github.com/submariner-io/submariner-operator/issues/1915
Fixes: #1919 
Signed-off-by: Sridhar Gaddam <sgaddam@redhat.com>

### CODE REVIEW

**Comment by sridhargaddam** [comment]
I could not test this PR as i am unable to deploy clusters on GCP, but the change should be sufficient AFAICT.

**Comment by sridhargaddam** [comment]
Just managed to deploy a GCP Cluster, now verifying the PR.

**Comment by sridhargaddam** [comment]
> Just managed to deploy a GCP Cluster, now verifying the PR.

Verified that the flag is properly passed to cloud-prepare and we are deploying dedicatedGW nodes

**Review by vthapar — APPROVED** [review]

**Review by mkolesnik — APPROVED** [review]

**Review by skitt — APPROVED** [review]

**Review by dfarrell07 — APPROVED** [review]

**Comment by sridhargaddam** [comment]
Backport PR: https://github.com/submariner-io/submariner-operator/pull/1928

**Pull request merged**
