### PR TITLE
fix volume hostPathType

### PR DESCRIPTION
**Pull request by jinglina**

### CODE REVIEW

**Comment by jinglina** [comment]
When kube-ovn was deployed in cluster, it won't get up for the volume. in kube-ovn, run/openvswitch/db.sock is used as a file. 
Otherwise, when calico as the cni plugin in the cluster ,this volum is not necessary, I suggest it be added optional depending on network cni.

**Review by skitt — CHANGES_REQUESTED** [review]
Please add your explanation from https://github.com/submariner-io/submariner-operator/pull/2127#issuecomment-1175931239 to the commit message.

**Comment by jinglina** [comment]
When volume hostPathType is not defined, the default "" will be added as pathType. When hostPathType= "", the path defined will be created as a folder. when kube-ovn is installed in the cluster, the path **/run/openvswitch/db.sock** will be used as a file, which will lead errors in kube-ovn project. At he same time, the path **/run/xtables.lock** is usually used as a file. So it is necessary to define hostPathType as "FileOrCreate".

**Comment by skitt** [comment]
Thanks for the added information, but please add it to your commit message, not the PR description and discussion. Run

    git commit --amend

to edit your message, then

    git push -f

to the appropriate remote.

**Comment by jinglina** [comment]
@skitt The e2e tests failed. I cannot tell why.

**Comment by skitt** [comment]
e2e is failing because of failed mounts:

    Warning  FailedMount  99s                  kubelet            Unable to attach or mount volumes: unmounted volumes=[host-run-openvswitch-db-sock], unattached volumes=[host-sys host-run-xtables-lock host-run-openvswitch-db-sock kube-api-access-lzht6]: timed out waiting for the condition
    Warning  FailedMount  94s (x9 over 3m42s)  kubelet            MountVolume.SetUp failed for volume "host-run-openvswitch-db-sock" : open /run/openvswitch/db.sock: no such file or directory

**Pull request closed without merging**
