### PR TITLE
Consolidate linting jobs

### PR DESCRIPTION
**Pull request by dfarrell07**
Combine all linting GHA jobs into one workflow, and update them to the
latest from the main Submariner repo.

Signed-off-by: Daniel Farrell <dfarrell@redhat.com>

### CODE REVIEW

**Review by mkolesnik — APPROVED** [review]

**Review by skitt — CHANGES_REQUESTED** [review]
The `golangci-lint` target needs to generate the embedded YAMLs; in the operator `Makefile`:

    golangci-lint: pkg/subctl/operator/common/embeddedyamls/yamls.go

(which will add to the prereqs defined in Shipyard’s `Makefile.inc`).

**Comment by dfarrell07** [comment]
@mangelajo This will require an update to the required checks. :pray:

**Review by skitt — APPROVED** [review]

**Review by tpantelis — APPROVED** [review]

**Comment by dfarrell07** [comment]
> Hmm - the merge button is disabled for me. Not sure why - I thought I had admin privs.

@tpantelis The DCO Check job name changed, and so the required check config on the GH Admin page needs to be updated to reflect the new name.

**Comment by tpantelis** [comment]
> > Hmm - the merge button is disabled for me. Not sure why - I thought I had admin privs.
> 
> @tpantelis The DCO Check job name changed, and so the required check config on the GH Admin page needs to be updated to reflect the new name.

Ahh - I missed that DCO check was still pending.

**Comment by dfarrell07** [comment]
This is ready for GH required checks edits @mangelajo/@tpantelis, and thanks! :pray:

**Pull request merged**
