### PR TITLE
Increase the E2E Full timeout to 45min

### PR DESCRIPTION
**Pull request by skitt**
The Lighthouse jobs are timing out with the current 30min limit. This
increases the timeout to match that used in Submariner.

Signed-off-by: Stephen Kitt <skitt@redhat.com>

### CODE REVIEW

**Review by Jaanki — APPROVED** [review]

**Review by dfarrell07 — APPROVED** [review]

**Comment by dfarrell07** [comment]
Related: https://github.com/submariner-io/lighthouse/pull/736

**Comment by skitt** [comment]
We’re hitting the timeouts on the 0.12 branch as well (see https://github.com/submariner-io/submariner-operator/actions/runs/2262447911/attempts/1), this should be backported.

**Review by mkolesnik — CHANGES_REQUESTED** [review]
This is a red herring and wont fix the issue, I'm investigating the failures on 0.12, don't merge for now please

**Comment by mkolesnik** [comment]
We should probably do https://github.com/submariner-io/enhancements/issues/45 instead of this

**Pull request closed without merging**
