### PR TITLE
Remove the --dataplane flag for deploy-broker

### PR DESCRIPTION
**Pull request by mangelajo**
As discussed recently in the slack channel, it's not working properly
and makes the list of flags for deploy-broker more complicated to
understand. This simplifies the picture.

Depends-On: https://github.com/submariner-io/shipyard/pull/205

### CODE REVIEW

**Comment by manosnoam** [comment]
Please fix commit spelling mistake "--dataplate"

Can you also explain why don't we need to deploy with dataplane anymore ?

**Comment by mangelajo** [comment]
Travis failed not sure why.. :?

**Comment by mangelajo** [comment]
> Please fix commit spelling mistake "--dataplate"
> 
> Can you also explain why don't we need to deploy with dataplane anymore ?
> 
> It should also be updated in Docs.

https://github.com/submariner-io/submariner-website/pull/178

**Comment by sridhargaddam** [comment]
> Travis failed not sure why.. :?

Could be some transient error.
fatal: couldn't find remote ref refs/pull/448/merge
The command "eval git fetch origin +refs/pull/448/merge: " failed. Retrying, 2 of 3.
fatal: couldn't find remote ref refs/pull/448/merge
The command "eval git fetch origin +refs/pull/448/merge: " failed. Retrying, 3 of 3.
fatal: couldn't find remote ref refs/pull/448/merge
The command "eval git fetch origin +refs/pull/448/merge: " failed 3 times.
The command "git fetch origin +refs/pull/448/merge:" failed and exited with 128 during .
Your build has been stopped.

**Pull request merged**
