### PR TITLE
Feature branch update

### PR DESCRIPTION
**Pull request by Billy99**
Merge devel into feature-multi-active-gw branch.

### CODE REVIEW

**Comment by skitt** [comment]
Note that you don’t need a branch in a fork to create this sort of PR: you can go to https://github.com/submariner-io/submariner-operator/compare/feature-multi-active-gw...devel and click on “Create pull request”.

**Comment by anfredette** [comment]
> Note that you don’t need a branch in a fork to create this sort of PR: you can go to [feature-multi-active-gw...devel](https://github.com/submariner-io/submariner-operator/compare/feature-multi-active-gw...devel) and click on “Create pull request”.

@skitt, thanks for the suggestion. If you do this and there are conflicts, do you then clone the pr branch and fix them locally?

**Comment by skitt** [comment]
> > Note that you don’t need a branch in a fork to create this sort of PR: you can go to [feature-multi-active-gw...devel](https://github.com/submariner-io/submariner-operator/compare/feature-multi-active-gw...devel) and click on “Create pull request”.
> 
> @skitt, thanks for the suggestion. If you do this and there are conflicts, do you then clone the pr branch and fix them locally?

Ah, yes, this does rather assume that there aren’t conflicts. If there are, then it’s probably easiest to create a branch in a fork...

**Comment by Billy99** [comment]
Closing this PR in favor of #2022.

As part of the rebase, I tried to remove #1951, which contained Multiple Active Gateway changes as well as a partial rebase. This caused merge conflict. The merge conflicts were fixed manually in the GUI, but there were two minor bugs in the addressing the merge conflict, that when fixed via the GUI cause DCO issue. Found it was easier to just start over than to try to fix that.

**Pull request closed without merging**
