### PR TITLE
Support diagnose tunnel on previous Submariner releases

### PR DESCRIPTION
**Pull request by sridhargaddam**
With some minor changes to the code, we will be able to support running
subctl diagnose tunnel command on previous Submariner releases where
NAT discovery is not enabled (or NAT discovery is still in progress).

Signed-Off-by: Sridhar Gaddam <sgaddam@redhat.com>

### CODE REVIEW

**Comment by nyechiel** [comment]
@SteveMattar FYI

**Comment by SteveMattar** [comment]
@sridhargaddam will this be backported to 0.9?

**Comment by sridhargaddam** [comment]
> @sridhargaddam will this be backported to 0.9?

Yes, we can @SteveMattar. It's a harmless change.

**Review by tpantelis — APPROVED** [review]

**Review by Jaanki — APPROVED** [review]

**Review by SteveMattar — APPROVED** [review]

**Review by mangelajo — APPROVED** [review]

**Comment by sridhargaddam** [comment]
Backport handled in the following PR - https://github.com/submariner-io/submariner-operator/pull/1507

**Pull request merged**
