### PR TITLE
Don't run some GHAs on drafts

### PR DESCRIPTION
**Pull request by Jaanki**
1. This PR enables skipping default e2e, cross builds and
upgrade GHA on PRs marked as draft.
2. When marked ready_for_review, these GHA will run on the PRs.
3. GHA will run if the draft PR has a label `test-draft`

Signed-Off-By: Janki Chhatbar <jchhatba@redhat.com>

### CODE REVIEW

**Comment by Jaanki** [comment]
As soon as I marked this PR as `draft`, `Cross-Build Checks`, `End to End Default` and `Upgrade` jobs were skipped.

Screenshot from 2022-01-04 16-21-50

**Comment by Jaanki** [comment]
and on marking the PR as `ready_for_review`, the jobs are triggered again

Screenshot from 2022-01-04 16-22-03

**Review by skitt — CHANGES_REQUESTED** [review]
I like to test draft PRs before marking them ready for review; it would be useful if the ready-to-test label could be used here to force tests of drafts.

**Comment by Jaanki** [comment]
> I like to test draft PRs before marking them ready for review; it would be useful if the ready-to-test label could be used here to force tests of drafts.

The idea behind this was to prevent heavy jobs from running on incomplete (draft) PRs. `ready-to-test` label will force full e2e to run. So using `test-draft` label.

**Review by skitt — APPROVED** [review]

**Review by nyechiel — APPROVED** [review]

**Review by tpantelis — APPROVED** [review]

**Pull request merged**
