### PR TITLE
Improve podCIDR detection

### PR DESCRIPTION
**Pull request by sridhargaddam**
In K8s, each node is typically assigned a unique PodCIDR range for the pods that run on that node. Each node's PodCIDR is used to allocate IP addresses to the pods scheduled on that node. Only if the cluster is a single node deployment, we should rely on the node.Spec.PodCIDR as podCIDR of the cluster.

Related to: https://github.com/submariner-io/submariner/issues/2128
Related to: https://github.com/submariner-io/submariner/issues/2489
Signed-off-by: Sridhar Gaddam <sgaddam@redhat.com>

### CODE REVIEW

**Review by skitt — APPROVED** [review]

**Comment by sridhargaddam** [comment]
This fix is not only for generic clusters but also for calico clusters.

**Review by yboaron — APPROVED** [review]

**Comment by dfarrell07** [comment]
@sridhargaddam Do you think this should be backported?

**Comment by sridhargaddam** [comment]
> @sridhargaddam Do you think this should be backported?

Yes @dfarrell07, this will be useful for environments like K3s. I'll handle the backports.

**Comment by sridhargaddam** [comment]
Release note PR: https://github.com/submariner-io/submariner-website/pull/1037

**Pull request merged**
