### PR TITLE
Support insecure connections to the broker in SD

### PR DESCRIPTION
**Pull request by skitt**
Propagate support for insecure connections in service discovery.

Signed-off-by: Stephen Kitt <skitt@redhat.com>

### CODE REVIEW

**Review by tpantelis — APPROVED** [review]

**Review by Jaanki — APPROVED** [review]

**Review by sridhargaddam — APPROVED** [review]

**Comment by m4ce** [comment]
@skitt @sridhargaddam  - we tried this change but it's not working. Where is this option actually used in the code?

**Comment by m4ce** [comment]
should it not be supported in

```func ForBroker(submariner *v1alpha1.Submariner, serviceDisc *v1alpha1.ServiceDiscovery) (*rest.Config, string, error)``` in ```submariner.Spec.BrokerK8sCA, &rest.TLSClientConfig{}```?

**Comment by skitt** [comment]
The option is used in Admiral to set up the Broker syncer, but I messed it up and the setting is passed incorrectly, sorry. I’m fixing that right now.

The `ForBroker` function is used in `subctl` only; it shouldn’t need an “insecure” flag (but I’m working on a separate set of changes which will allow that too).

**Comment by skitt** [comment]
Fixed with https://github.com/submariner-io/submariner-operator/pull/1692 (at least, the setting will be passed correctly).

**Comment by m4ce** [comment]
Thanks @skitt - let us know when it's ready to be tested. We are quite eager to try it out asap.

**Comment by Hitesh-Agrawal** [comment]
@skitt Waiting to test the same. Pls share the details on which submariner-operator helm chart to use and with which docker image.

**Pull request merged**
