### PR TITLE
Stop filling in token/CA in the Submariner CR

### LINKED ISSUE #1869: Stop publishing sensitive information directly in CRs
Now that the PSK and broker token are stored in secrets, we should stop publishing them directly in CRs.

This won’t really improve security, but it will make CR dumps easier to read.

This follows on from https://github.com/submariner-io/submariner/issues/326.

Depends on https://github.com/submariner-io/subctl/issues/631

### PR DESCRIPTION
**Pull request by skitt**
This ensures we rely only on the secret containing the broker access token.

Fixes: #1869

Depends on https://github.com/submariner-io/releases/issues/644
Depends on https://github.com/submariner-io/subctl/issues/631

### CODE REVIEW

**Review by tpantelis — APPROVED** [review]

**Review by mkolesnik — APPROVED** [review]

**Comment by dfarrell07** [comment]
@skitt Why does this depend on RC0? Should it be the other way around, or am I missing something about why an API change should be after the RC?

**Comment by skitt** [comment]
> @skitt Why does this depend on RC0? Should it be the other way around, or am I missing something about why an API change should be after the RC?

This depends on rc0 so that it isn’t included in 0.15. It will be merged to `devel` after we cut the 0.15 branch, so it will target 0.16 — I want to make sure it gets as much testing as possible before it gets released.

**Comment by nyechiel** [comment]
@skitt is it the right time to merge this and move to the 0.16 board?

**Comment by skitt** [comment]
> @skitt is it the right time to merge this and move to the 0.16 board?

This will break `recover-broker-info`, so we need to address that first (https://github.com/submariner-io/subctl/issues/631).

**Comment by nyechiel** [comment]
> > @skitt is it the right time to merge this and move to the 0.16 board?
> 
> This will break `recover-broker-info`, so we need to address that first ([submariner-io/subctl#631](https://github.com/submariner-io/subctl/issues/631)).

Is this planned for 0.16? It seems to be it in the backlog board at the moment

**Comment by skitt** [comment]
> > > @skitt is it the right time to merge this and move to the 0.16 board?
> > 
> > 
> > This will break `recover-broker-info`, so we need to address that first ([submariner-io/subctl#631](https://github.com/submariner-io/subctl/issues/631)).
> 
> Is this planned for 0.16? It seems to be it in the backlog board at the moment

We didn’t finish planning 0.16 yesterday...

**Comment by tpantelis** [comment]
Is this still relevant?

**Pull request closed without merging**
