### PR TITLE
Make devel the default version, use a variable

### PR DESCRIPTION
**Pull request by mangelajo**

### CODE REVIEW

**Review by skitt — CHANGES_REQUESTED** [review]
Could you explain, in the commit message, what the point of using a variable is?

**Comment by mangelajo** [comment]
> Could you explain, in the commit message, what the point of using a variable is?

Yes, also, we need to figure out when to override the var. At tag?, if so... what happens for a release like 0.7.0-pre0 which didn't have matching submariner/lighthouse? 

May be we could detect such tag doesn't exist and leave just "devel"?

**Comment by skitt** [comment]
> > Could you explain, in the commit message, what the point of using a variable is?
> 
> Yes, also, we need to figure out when to override the var. At tag?, if so... what happens for a release like 0.7.0-pre0 which didn't have matching submariner/lighthouse?
> 
> May be we could detect such tag doesn't exist and leave just "devel"?

We’d have to tag before building, or rebuild after tagging... And yes, unsynchronised releases would be a pain! Perhaps we could rely on the version of the module we import...

**Comment by mangelajo** [comment]
Ok, dropping this for a bigger plan we made.

**Pull request closed without merging**
