### PR TITLE
Change RHOS default image type in subctl

### PR DESCRIPTION
**Pull request by aswinsuryan**
Change the RHOS image type to a smaller one which is sufficient
for a submariner g/w node.

Signed-off-by: Aswin Suryanarayanan <aswinsuryan@gmail.com>

### CODE REVIEW

**Review by dfarrell07 — APPROVED** [review]

**Comment by dfarrell07** [comment]
Should this be backported?

**Review by Jaanki — APPROVED** [review]

**Comment by aswinsuryan** [comment]
> Should this be backported?
yes I added the label

**Comment by Jaanki** [comment]
@aswinsuryan if you are backporting, can you please try using `make LOCAL_BUILD=1 backport release=release-0.12 pr=1973`. [Backport section](https://submariner.io/development/backports/) on the website explains the process in details. It will automatically add `backport-handled` label to this PR.

**Comment by aswinsuryan** [comment]
> make LOCAL_BUILD=1 backport release=release-0.12 pr=1973

@Jaanki it did not work

 `$ make LOCAL_BUILD=1 backport release=release-0.12 pr=1973
Makefile:47: ../shipyard/Makefile.inc: No such file or directory
make: *** No rule to make target '../shipyard/Makefile.inc'.  Stop.`

**Comment by skitt** [comment]
> `$ make LOCAL_BUILD=1 backport release=release-0.12 pr=1973 Makefile:47: ../shipyard/Makefile.inc: No such file or directory make: *** No rule to make target '../shipyard/Makefile.inc'. Stop.`

You need to have Shipyard cloned alongside your project; see https://submariner.io/development/backports/#standalone-pull-requests

**Comment by aswinsuryan** [comment]
> > `$ make LOCAL_BUILD=1 backport release=release-0.12 pr=1973 Makefile:47: ../shipyard/Makefile.inc: No such file or directory make: *** No rule to make target '../shipyard/Makefile.inc'. Stop.`
> 
> You need to have Shipyard cloned alongside your project; see https://submariner.io/development/backports/#standalone-pull-requests

it worked , thanks

**Review by skitt — APPROVED** [review]

**Pull request merged**
