### PR TITLE
Rename csv file from `submariner` to `submariner-operator`

### PR DESCRIPTION
**Pull request by Jaanki**
See individual commits for details.

Signed-off-by: Janki Chhatbar <jchhatba@redhat.com>

### CODE REVIEW

**Comment by skitt** [comment]
To avoid the interactive questions, this needs `--package submariner` to be added to the `generate kustomize manifests` line, or the `projectName` to be changed to `submariner` in `PROJECT`.

The extra `role.yaml` file is generated by the `controller-gen` step.

**Comment by Jaanki** [comment]
Reference: https://github.com/operator-framework/operator-sdk/issues/6028#issuecomment-1266081773

**Review by skitt — CHANGES_REQUESTED** [review]
This doesn’t work as-is:

```
$ make bundle
Makefile:104: warning: overriding recipe for target 'e2e'
/home/skitt/go/src/github.com/submariner-io/shipyard/Makefile.inc:171: warning: ignoring old recipe for target 'e2e'
/home/skitt/go/src/github.com/submariner-io/submariner-operator/bin/controller-gen "crd:crdVersions=v1" rbac:roleName=manager-role webhook paths="./..." output:crd:artifacts:config=config/crd/bases
/home/skitt/go/src/github.com/submariner-io/submariner-operator/bin/operator-sdk generate kustomize manifests -q

Display name for the operator (required): 
> 
```

The project name in `PROJECTS` doesn’t match the file name for the base CSV.

**Comment by skitt** [comment]
> The project name in `PROJECTS` doesn’t match the file name for the base CSV.

Apologies, my local copy of the PR was outdated. However the current version doesn’t work either:

```
$ make kustomization bundle
Makefile:104: warning: overriding recipe for target 'e2e'
/home/skitt/go/src/github.com/submariner-io/shipyard/Makefile.inc:171: warning: ignoring old recipe for target 'e2e'
/home/skitt/go/src/github.com/submariner-io/submariner-operator/bin/controller-gen "crd:crdVersions=v1" rbac:roleName=manager-role webhook paths="./..." output:crd:artifacts:config=config/crd/bases
/home/skitt/go/src/github.com/submariner-io/submariner-operator/bin/operator-sdk generate kustomize manifests -q
(cd config/manifests && /home/skitt/go/src/github.com/submariner-io/submariner-operator/bin/kustomize edit set image controller=quay.io/submariner/submariner-operator:devel-ca125764 && \
 /home/skitt/go/src/github.com/submariner-io/submariner-operator/bin/kustomize edit set image repo=quay.io/submariner)
sed -e 's/${VERSION}/0.14.0/g' config/bundle/kustomization.template.yaml > config/bundle/kustomization.yaml
sed -e 's/${REPLACES_OP}//g' -e 's/${FROM_VERSION}/0.0.0/g' \
	config/bundle/patches/submariner.csv.template.yaml > config/bundle/patches/submariner.csv.config.yaml
(cd config/bundle && \
/home/skitt/go/src/github.com/submariner-io/submariner-operator/bin/kustomize edit add annotation createdAt:"2022-10-17 18:19:20" -f)
(/home/skitt/go/src/github.com/submariner-io/submariner-operator/bin/kustomize build /home/skitt/go/src/github.com/submariner-io/submariner-operator/config/manifests \
| /home/skitt/go/src/github.com/submariner-io/submariner-operator/bin/operator-sdk generate bundle -q --overwrite --version 0.14.0 --channels=alpha-0.14 --default-channel=alpha-0.14)
INFO[0002] Creating bundle/metadata/annotations.yaml    
INFO[0002] Creating bundle.Dockerfile                   
INFO[0002] Bundle metadata generated suceessfully       
(cd config/bundle && /home/skitt/go/src/github.com/submariner-io/submariner-operator/bin/kustomize edit add resource ../../bundle/manifests/submariner.clusterserviceversion.yaml)
/home/skitt/go/src/github.com/submariner-io/submariner-operator/bin/kustomize build config/bundle/ --load_restrictor=LoadRestrictionsNone --output bundle/manifests/submariner.clusterserviceversion.yaml
Error: var '{SUBMARINER_OPERATOR_IMAGE operators.coreos.com_v1alpha1_ClusterServiceVersion {spec.install.spec.deployments.0.spec.template.spec.containers.0.image}}' cannot be mapped to a field in the set of known resources
make: *** [Makefile:195: bundle] Error 1
```

**Comment by Jaanki** [comment]
> > The project name in `PROJECTS` doesn’t match the file name for the base CSV.
> 
> Apologies, my local copy of the PR was outdated. However the current version doesn’t work either:
> 

That was older version of this PR.

**Comment by skitt** [comment]
The latest PR still fails on my system:

```
/home/skitt/go/src/github.com/submariner-io/submariner-operator/bin/controller-gen "crd:crdVersions=v1" rbac:roleName=manager-role webhook paths="./..." output:crd:artifacts:config=config/crd/bases
/home/skitt/go/src/github.com/submariner-io/submariner-operator/bin/operator-sdk generate kustomize manifests -q
(cd config/manifests && /home/skitt/go/src/github.com/submariner-io/submariner-operator/bin/kustomize edit set image controller=quay.io/submariner/submariner-operator:devel-ee912d54 && \
 /home/skitt/go/src/github.com/submariner-io/submariner-operator/bin/kustomize edit set image repo=quay.io/submariner)
sed -e 's/${VERSION}/0.14.0/g' config/bundle/kustomization.template.yaml > config/bundle/kustomization.yaml
sed -e 's/${REPLACES_OP}//g' -e 's/${FROM_VERSION}/0.0.0/g' \
	config/bundle/patches/submariner.csv.template.yaml > config/bundle/patches/submariner.csv.config.yaml
(cd config/bundle && \
/home/skitt/go/src/github.com/submariner-io/submariner-operator/bin/kustomize edit add annotation createdAt:"2022-10-31 11:51:13" -f)
(/home/skitt/go/src/github.com/submariner-io/submariner-operator/bin/kustomize build /home/skitt/go/src/github.com/submariner-io/submariner-operator/config/manifests \
| /home/skitt/go/src/github.com/submariner-io/submariner-operator/bin/operator-sdk generate bundle -q --overwrite --version 0.14.0 --channels=alpha-0.14 --default-channel=alpha-0.14)
INFO[0000] Creating bundle.Dockerfile                   
INFO[0000] Creating bundle/metadata/annotations.yaml    
INFO[0000] Bundle metadata generated suceessfully       
(cd config/bundle && /home/skitt/go/src/github.com/submariner-io/submariner-operator/bin/kustomize edit add resource ../../bundle/manifests/submariner.clusterserviceversion.yaml)
/home/skitt/go/src/github.com/submariner-io/submariner-operator/bin/kustomize build config/bundle/ --load_restrictor=LoadRestrictionsNone --output bundle/manifests/submariner.clusterserviceversion.yaml
Error: var '{SUBMARINER_OPERATOR_IMAGE operators.coreos.com_v1alpha1_ClusterServiceVersion {spec.install.spec.deployments.0.spec.template.spec.containers.0.image}}' cannot be mapped to a field in the set of known resources
make: *** [Makefile:195: bundle] Error 1
```

Please add a GHA to test bundle creation on CI.

**Comment by skitt** [comment]
I’ve split out https://github.com/submariner-io/submariner-operator/pull/2314 while we figure out what’s wrong with the bundle from the second commit.

**Comment by nyechiel** [comment]
I think we should convert this to draft at this point?

**Comment by nyechiel** [comment]
@Jaanki is this still planned for 0.15?

**Comment by skitt** [comment]
This breaks bundle construction and won’t be merged.

**Pull request closed without merging**
