### PR TITLE
Pass a filled-in SubmarinerSpec

### PR DESCRIPTION
**Pull request by skitt**
This reduces the number of arguments to deploy.Ensure().

Signed-off-by: Stephen Kitt <skitt@redhat.com>

---
This change is [Reviewable](https://reviewable.io/reviews/submariner-io/submariner-operator/57)

### CODE REVIEW

**Comment by skitt** [comment]
TBH I’m not sure this is the best approach, but it feels overkill to create another data structure...

**Comment by skitt** [comment]
Oh, also, I’ll rebase this on top of #56 once that’s merged.

**Comment by skitt** [comment]
> unrelated sidenote and easy patch... we could want to add a flag for enabling submariner debugging "--submariner-debug" or something like that?

Yes, I’ve got a patch ready for that, but it builds on top of this one so to keep reviews easy I was waiting for this to be merged.

**Comment by mangelajo** [comment]
@skitt I was going to merge, but I saw it's now conflicting ^

**Pull request merged**
